embedding_size: 64
feat_embed_dim: 64
weight_size: [64, 64]

lambda_coeff: 0.9
reg_weight: 0.001

n_mm_layers: 1
n_ui_layers: 2
knn_k: 10

mm_image_weight: 0.1
dropout: 0.8

hyper_parameters: ["num_layers", "d_conv", "expand", "dropout_prob", ]

hidden_size: 64                    # (int) Number of features in the hidden state.
num_layers: [1, 2, 3, 4, 5, 6, 7, 8, 9]                      # (int) Number of Mamba layers.
dropout_prob: [0.1, 0.2, 0.3, 0.8, 0.9]                  # (float) Dropout rate.

d_state: [16, 32, 64]                   # (int) SSM state expansion factor
d_conv: [2, 4]                    # (int) Local convolution width
expand: [2, 4]                     # (int) Block expansion factor