embedding_size: 64
feat_embed_dim: 64
weight_size: [64, 64]

lambda_coeff: 0.9
reg_weight: 0.001

n_mm_layers: 1
n_ui_layers: 2
knn_k: 10

mm_image_weight: 0.1
dropout: 0.8

hyper_parameters: []

hidden_size: 64                    # (int) Number of features in the hidden state.
num_layers: 6                     # (int) Number of Mamba layers.
dropout_prob: 0.1                  # (float) Dropout rate.

d_state: 64                  # (int) SSM state expansion factor
d_conv: 4                    # (int) Local convolution width
expand: 4                    # (int) Block expansion factor
